# Generated by Django 5.2.4 on 2025-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuginnWatch', '0003_server_added_on_alter_server_name_alter_server_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='ports',
            field=models.TextField(default='No data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanresult',
            name='raw_output',
            field=models.TextField(default='No data'),
            preserve_default=False,
        ),
    ]
