# Generated by Django 5.2.4 on 2025-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuginnWatch', '0004_scanresult_ports_scanresult_raw_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='ports',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='raw_output',
            field=models.TextField(default='No data'),
        ),
    ]
