# Generated by Django 5.2.4 on 2025-08-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuginnWatch', '0006_scanresult_cves_alter_scanresult_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='cves',
        ),
    ]
