# Generated by Django 5.2.4 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuginnWatch', '0007_remove_scanresult_cves'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='cves',
            field=models.TextField(blank=True, default='No CVE info available.'),
        ),
    ]
