# Generated by Django 5.2.4 on 2025-08-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuginnWatch', '0008_scanresult_cves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='cves',
        ),
    ]
